REM  If you want to play with your users from a DOS prompt, you can.  But
REM  if your LORD uses Internal Modules, you will need to use LORDCFG.EXE
REM  to set up ANOTHER node, use LOCAL as the BBSTYPE, and from then on
REM  run LORD with 'START (node number you specified as local)' and that
REM  will do it.  


REM this is the quick and dirty way. (LORD will play you under node 1)

START.BAT 1 /L 
